#spring:
#  datasource:
#    dynamic:
#      primary: app          # 默认数据源
#      strict: true            # 严格模式，未匹配的数据源报错
#      datasource:
#        admin:
#          url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?currentSchema=admin&useSSL=false&stringtype=unspecified
#          username: postgres.roritoxjmogptydczrjn
#          password: wanghengrun12300..
#          driver-class-name: org.postgresql.Driver
#        app:
#          url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?currentSchema=app&useSSL=false&stringtype=unspecified
#          username: postgres.roritoxjmogptydczrjn
#          password: wanghengrun12300..
#          driver-class-name: org.postgresql.Driver

spring:
  datasource:
    dynamic:
      primary: app          # 默认数据源
      strict: true            # 严格模式，未匹配的数据源报错
      datasource:
        admin:
          url: jdbc:postgresql://101.201.57.221:5432/root?currentSchema=admin&useSSL=false&stringtype=unspecified
          username: root
          password: root
          driver-class-name: org.postgresql.Driver
        app:
          url: jdbc:postgresql://101.201.57.221:5432/root?currentSchema=app&useSSL=false&stringtype=unspecified
          username: root
          password: root
          driver-class-name: org.postgresql.Driver